### ISSUE TITLE
hostile.set allows for hostname='' (empty string)

### ISSUE THREAD

**Issue by Eeemil** [feross/hostile#38]
Perhaps it would be neat to perform some simple hostname validation too, see https://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it fixed, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
